# Nested looops

In [6]:
# çarpım tablosu örneği
for i in range(1,6):         # satır
    for j in range(1,10):    # sütun
        print(f"{i*j}\t", end="")
    print()  # içteki işin bitince (sütundaki ilerlemen bitince) bir alt satıra geç


1	2	3	4	5	6	7	8	9	
2	4	6	8	10	12	14	16	18	
3	6	9	12	15	18	21	24	27	
4	8	12	16	20	24	28	32	36	
5	10	15	20	25	30	35	40	45	


In [9]:
# çarpım tablosu örneği
for i in range(1,11):         # satır
    for j in range(1,11):    # sütun
        print(f"{i}*{j}={i*j}\t", end="")
    print()  # içteki işin bitince (sütundaki ilerlemen bitince) bir alt satıra geç

1*1=1	1*2=2	1*3=3	1*4=4	1*5=5	1*6=6	1*7=7	1*8=8	1*9=9	1*10=10	
2*1=2	2*2=4	2*3=6	2*4=8	2*5=10	2*6=12	2*7=14	2*8=16	2*9=18	2*10=20	
3*1=3	3*2=6	3*3=9	3*4=12	3*5=15	3*6=18	3*7=21	3*8=24	3*9=27	3*10=30	
4*1=4	4*2=8	4*3=12	4*4=16	4*5=20	4*6=24	4*7=28	4*8=32	4*9=36	4*10=40	
5*1=5	5*2=10	5*3=15	5*4=20	5*5=25	5*6=30	5*7=35	5*8=40	5*9=45	5*10=50	
6*1=6	6*2=12	6*3=18	6*4=24	6*5=30	6*6=36	6*7=42	6*8=48	6*9=54	6*10=60	
7*1=7	7*2=14	7*3=21	7*4=28	7*5=35	7*6=42	7*7=49	7*8=56	7*9=63	7*10=70	
8*1=8	8*2=16	8*3=24	8*4=32	8*5=40	8*6=48	8*7=56	8*8=64	8*9=72	8*10=80	
9*1=9	9*2=18	9*3=27	9*4=36	9*5=45	9*6=54	9*7=63	9*8=72	9*9=81	9*10=90	
10*1=10	10*2=20	10*3=30	10*4=40	10*5=50	10*6=60	10*7=70	10*8=80	10*9=90	10*10=100	


In [ ]:
calisan = ["Doğu", "Özge", "Ceren","Emre","Fatma"]
mod = ["mutlu", "mutsuz", "nötr"]
for c in calisan:
    for m in mod:
        print(c, m)
    print()

In [ ]:
calisan = ["Doğu", "Özge", "Ceren","Emre","Fatma"]
zaman = ["bugün", "her zaman"]
mod = ["mutlu", "mutsuz", "nötr"]

for c in calisan:
    for z in zaman:
        for m in mod:
            print(c, z, m)
    print()

In [17]:
#01234
"ATATÜRK"[4]  #4.indisli karakteri

'Ü'

In [15]:
text = "ATATÜRK"
for i in range(1,len(text)+1):        #for i in range(7):
    for j in range(i):
        print(text[j], end="") 
    print()                    # 

A
AT
ATA
ATAT
ATATÜ
ATATÜR
ATATÜRK


In [23]:
j = 1
for i in range(1,11):
    print(f"{i*j}\t", end="")
    j+=1
      

1	4	9	16	25	36	49	64	81	100	

In [26]:
import random
katilanlar = [ "Doğu", "Özge", "Ceren","Emre","Fatma"]
print("Günün Talihlisi...: ")
talihli = random.choice(katilanlar) #listeden rastgele birini al
print(talihli)

Günün Talihlisi...: 
Emre


In [41]:
from random import sample
#sample: listeden k adet örnek seçer
sample(['red', 'red', 'red', 'yellow', 'blue', 'blue'], k=3)

['yellow', 'blue', 'red']

In [48]:
# Sayısal Loto
import random
nums = range(1,50)
loto_nums = random.sample(nums, k=6)
print("Loto.:", loto_nums)

Loto.: [48, 30, 17, 4, 43, 42]


In [56]:
# Sayısal Loto
import random
random.seed(101)  # rastgele üretilen sonucu sabitlemek için kullanılır
nums = range(1,50)
loto_nums = random.sample(nums, k=6)
print("Loto.:", loto_nums)

Loto.: [38, 13, 35, 23, 30, 4]


In [52]:
import random
random.randint(1,5)  #5 dahil

5

In [54]:
#sayısal loto: randint
import random
random.seed(100)  # rastgele üretilen sonucu sabitlemek için kullanılır
loto_nums = []
print("Loto.:")
for i in range(6):
    loto_nums.append(random.randint(1,49))  # listeye üretileni ekler

#listeyi yazdır
print(loto_nums)

Loto.:
[10, 30, 30, 12, 46, 26]


In [ ]:
#Soru: Yukarıdaki listede tekrarlı sayıları nasıl kaldırıp, yeni sayılar üretebiliriz.

In [62]:
#Sayı tahmin oyunu
import random
tutulan = random.randint(1,100)  # bilg. tuttuğu sayı
puan = 100
while True:
    tahmin = int(input("Tahmininiz.:"))
    if tahmin==tutulan:
        print("Bravo bildiniz")
        break  # döngüden çık
    elif tahmin<tutulan:
        print("Daha büyük giriniz")
        puan = puan - 10
    else:
        print("Daha küçük sayı giriniz")
        puan = puan - 10

print("Puanınız.:", puan)

Tahmininiz.:45
Daha küçük sayı giriniz
Tahmininiz.:35
Daha büyük giriniz
Tahmininiz.:39
Daha küçük sayı giriniz
Tahmininiz.:37
Bravo bildiniz
Puanınız.: 70


In [109]:
# Password generator: 
import random
import string
kucuk_harf = random.sample(string.ascii_lowercase,2) # 2 adet karakteri liste halinde verir
buyuk_harf = random.sample(string.ascii_uppercase,2) # 2 adet karakteri liste halinde verir
rakam = random.sample(string.digits,2) # 2 adet karakteri liste halinde verir
ozel_karakter = random.sample(string.punctuation,2)
sifre = kucuk_harf + buyuk_harf + rakam + ozel_karakter
random.shuffle(sifre)
print(sifre)  # liste halinde
# listeyi stringe dönüştür
print("".join(sifre))

['|', 'J', 'a', '9', 'U', 'q', '&', '6']
|Ja9Uq&6


In [113]:
if sifre[0].isalnum():
    print(sifre)
else:
    random.shuffle(sifre) #kariştir
    print(sifre)  # yeniden yaz

['q', '9', 'J', 'a', '6', 'U', '|', '&']


# indis kavramı

In [114]:
#indis: 0123456
#neg.  -7 .. -1
text = "ATATÜRK"
# ilk harfi al
text[0]

'A'

In [115]:
#son karakteri al
text[6]

'K'

In [117]:
text[len(text)-1]

'K'

In [116]:
text[-1]  #son karateri al

'K'

In [118]:
# Bir sayı listesindeki en büyük 2. sayıyı nasıl buluruz?
nums = [4,5,6,2,9,12,34,9,63,5]
#küçükten büyüğe sıralyıp, en sondaki 2.eleman(-2. indisli elemanı) alabiliriz
nums.sort()
print(nums)
print(nums[-2])

[2, 4, 5, 5, 6, 9, 9, 12, 34, 63]
34


In [120]:
nums = [4,5,6,2,9,12,34,9,63,5]
#küçükten büyüğe sıralyıp, en sondaki 2.eleman(-2. indisli elemanı) alabiliriz
nums.sort()[-2]

TypeError: ignored

In [122]:
# slicing(dilimleme) [start:stop-1:step]
#indis  0123456
text = "ATATÜRK"
text[:3]

'ATA'

In [123]:
#indis  0123456
text = "ATATÜRK"
text[3:]

'TÜRK'

In [125]:
#indis  0123456
text = "ATATÜRK"
text[2:5]

'ATÜ'

In [124]:
#ters çevir
text = "ATATÜRK"
text[::-1]

'KRÜTATA'

In [129]:
text = "ATATÜRK"
#      -7-6-5-4-3-2-1
print(text)
for a in range(1,len(text)):
    print(text[:-a])

ATATÜRK
ATATÜR
ATATÜ
ATAT
ATA
AT
A


In [131]:
#Soru: bir textin 3.indisli karakterini nasıl silebiliriz
#       012345
text = "python"  #çözüm-1
text = text[:3] + text[4:]
print(text)

pyton


In [132]:
text="PYTHON"  #çözüm-2
sonuc = text.replace("H","")
print(sonuc)

PYTON


In [133]:
#       012345
text = "python"
text[3] = ""  #str veri immutable özellikli
print(text)

TypeError: ignored

In [136]:
#çözüm-3 listeye dönüştürüp doğrudan değiştirebilirim
#listeler mutable özellikli 
text = "python"
lis_text = list(text)
lis_text[3] = ""  # list veri mutable özellikli
print(lis_text)
text = "".join(lis_text)
print(text)

['p', 'y', 't', '', 'o', 'n']
pyton


In [138]:
#girilen bir textin palindrom olup olmadığını test etmek için
text = input()
if text==text[::-1]:
    print("palindrom")
else:
    print("palindrom değil")

adam
palindrom değil


In [139]:
# girilen bir textin palindrom olup olmadığını test et, 
# eğer palindrom değilse palindrom yap
text = input()
if text==text[::-1]:
    print("palindrom")
else:
    print("palindrom değil")
    text = text + text[::-1]
    print("artık palindrom oldu..:", text)

adam
palindrom değil
artık palindrom oldu..: adammada


In [ ]:
# Listeye eleman ekleme metotları
"""
list.append(x) : Add an item to the end of the list. Equivalent to a[len(a):] = [x].

list.extend(iterable): Extend the list by appending all the items from the iterable. Equivalent to a[len(a):] = iterable.

list.insert(i, x) : Insert an item at a given position. 
"""

In [140]:
bos_list = []
bos_list.append(1)
bos_list.append(2)
bos_list.append(3)
print(bos_list)

[1, 2, 3]


In [141]:
liste2 = [5,6,7,8]
bos_list.append(liste2)
print(bos_list)

[1, 2, 3, [5, 6, 7, 8]]


In [143]:
bos_list = []
bos_list.append(1)
bos_list.append(2)
bos_list.append(3)
print(bos_list)
liste2 = [5,6,7,8]
bos_list.extend(liste2)
print(bos_list)

[1, 2, 3]
[1, 2, 3, 5, 6, 7, 8]


In [145]:
liste = [3,4,6,7,8]
#araya (2. indisli) 5 sayısını eklemek için;
liste.insert(2, 5)
print(liste)

[3, 4, 5, 6, 7, 8]


In [ ]:
range(3) # 0,1,2

In [148]:
x = ['a','b','c']
for i in range(len(x)):
    x.append(i)
print(x)

['a', 'b', 'c', 0, 1, 2]


In [149]:
x = ['a','b','c']
for i in range(len(x)):
    x.append(str(i))
print(x)

['a', 'b', 'c', '0', '1', '2']


In [150]:
x = ['a','b','c']
for i in range(len(x)):
    x.append(x[i])
print(x)

['a', 'b', 'c', 'a', 'b', 'c']


In [151]:
x = []
for i in range(10):
    x.append(i)
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [152]:
#liste üreteci
x = [i for i in range(10)]
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [154]:
x = []
for i in range(10):
    if i%2==0:
        x.append(i)
print(x)

[0, 2, 4, 6, 8]


In [155]:
#yukarıdakinin kısaltılmış formu
x = [i for i in range(10) if i%2==0 ]
print(x)

[0, 2, 4, 6, 8]


In [156]:
x = []
for i in range(10):
    if i%2==0:
        x.append(i)
    else:
        x.append(i**2)
print(x)

[0, 1, 2, 9, 4, 25, 6, 49, 8, 81]


In [157]:
x = [i if i%2==0 else i**2 for i in range(10)]
print(x)

[0, 1, 2, 9, 4, 25, 6, 49, 8, 81]


In [158]:
[i for i  in range(100,0,-10)]

[100, 90, 80, 70, 60, 50, 40, 30, 20, 10]

In [160]:
#11- Verilen metindeki sesli harfleri kaldıran program
text = "Bu akşam Ankaraya gidiyorum"
sessiz_harfler = []
for i in text:
    if i not in "aeiouüıö":
        sessiz_harfler.append(i)
print("".join(sessiz_harfler)) 

B kşm Ankry gdyrm


In [161]:
text = "Bu akşam Ankaraya gidiyorum"
sessiz_harfler = [i for i in text if i not in "aeiouüıö"]
print("".join(sessiz_harfler)) 

B kşm Ankry gdyrm


In [164]:
for i in "python":
    print(i, end="")

python

In [165]:
for a in range(0,12,2):
    if a==6:
        break
    print(a, end=" ")

0 2 4 

In [167]:
for i in [1,2,3,4]:
    if i==3:
        continue  # alttaki satırı gözardı et(atla)
    print(f"{i}.kat", end=" ")

1.kat 2.kat 4.kat 

In [168]:
# Sayısal Array(klasik dizi) Oluşturma
import numpy as np
np.random.randint(1,20,10) #1-20 arası 10 adet sayı üret

array([15,  1, 12,  3,  8, 10, 13, 14,  9, 11])

In [169]:
print(np.random.randint(1,20,10)) #1-20 arası 10 adet sayı üret

[ 4  6 10  5 13 11 15  5 14  3]


In [174]:
np.random.seed(100)
print(np.random.randint(1,50,6)) #sayısal loto

[ 9 25  4 40 24 16]


In [175]:
# 0-10 arası 0.5 lik artım ile sayılar üret
range(0,10,0.5)

TypeError: ignored

In [177]:
# 0-10 arası 0.5 lik artım ile sayılar üret
import numpy as np
print(np.arange(0,10,0.5))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [179]:
# eşit aralıklı saylar üretmek np.linspace kullanılabilir.
np.linspace(0,10,5)  # 0-10 arası 5 sayı üret

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [182]:
np.linspace(0,100,10)  # 0-100 arası 10 sayı üret

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [183]:
np.linspace(0,100,10, dtype=int)  # 0-100 arası 10 tamsayı üret

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [184]:
#matris: 2 boyutlu dizi
# 3 satır 4 sütundan oluşan bir dizi, bütün elemalar sıfır olsun
matris_3_4 = np.zeros((3,4))
print(matris_3_4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [186]:
# 3 satır 4 sütundan oluşan bir dizi, bütün elemalar rasgele 0-1 olsun
matris_3_4 = np.random.rand(3,4)
print(matris_3_4)

[[0.84477613 0.00471886 0.12156912 0.67074908]
 [0.82585276 0.13670659 0.57509333 0.89132195]
 [0.20920212 0.18532822 0.10837689 0.21969749]]


In [194]:
# rasgele sayı üret
nums= np.random.randn(100)
print(nums)

[-1.050555   -0.64326693 -0.50219939 -3.00081157  0.28667885  0.49880758
 -0.60366109  1.30894109  1.27590944 -1.28599308 -0.62575643  0.34171079
 -0.13077302 -1.09164964  0.07453901  1.24824825 -0.45034291 -0.34752287
 -0.31749028  1.01295224 -0.83819674 -1.04132454 -0.08728565  1.15308879
  1.06793875  0.57034207 -0.27299617 -0.16039752 -0.01301953  0.62186687
  1.37417875  0.77965412 -1.5546354  -1.76482361 -0.66898474  1.74108588
  0.07353037  0.07590027 -0.19616725 -0.42529073  0.63221163 -0.01063153
 -0.59913161  0.9047258  -1.39672651  1.95303272  0.89669724  0.21041814
 -0.38981342  2.95201603 -1.14432764 -0.873981   -0.83160684  0.08417013
  1.18952505  0.5443334   0.10254572  0.25258007 -2.82736291 -2.26931098
  0.13730702 -0.02477473 -0.97571415  2.02226211 -0.51282784  0.65215822
  0.60413177 -0.88366827  0.18395205  1.11604602  0.80623901  1.56796229
  1.10604223  0.1817366   0.5420871  -0.3525323   1.65592674 -0.46807102
 -1.28003524 -0.36169448 -1.00495565  0.79825243  0

In [198]:
liste = [1,2,4,3]
copy_lis = liste
copy_lis.append(7)  #copy_lis e eklendi
print(liste)
print(id(copy_lis))
print(id(liste))

[1, 2, 4, 3, 7]
140531729404480
140531729404480


In [199]:
liste = [1,2,4,3]
copy_lis = liste.copy()  # yeni bir nensne oluştu
copy_lis.append(7)  #copy_lis e eklendi
print(liste)
print(id(copy_lis))
print(id(liste))

[1, 2, 4, 3]
140531729050816
140531732770496


In [200]:
lis = []
lis.append(3)  
lis.extend("a")
lis.extend([1,2])
print(lis)

[3, 'a', 1, 2]


In [201]:
lis = []
lis.append(3)  
lis.extend("a")
lis.append([1,2])
print(lis)

[3, 'a', [1, 2]]


In [202]:
numbers = [3,4,5,6]
#liste sonuna 7 ekleme
numbers.insert(len(numbers), 7) 
print(numbers)

[3, 4, 5, 6, 7]


In [204]:
(x:=[1,2,3]).extend(x)
print(x)

[1, 2, 3, 1, 2, 3]


In [205]:
(x:=[1,2,3]).append(x)
print(x)

[1, 2, 3, [...]]


In [206]:
numbers = [3,4,5,6]
#listeden 5'i sil
numbers.remove(5)
print(numbers)

[3, 4, 6]


In [207]:
numbers = [3,4,5,6]
#listeden 5'i sil
numbers.pop(2)  #.pop(indis)
print(numbers)

[3, 4, 6]


In [208]:
numbers = [3,4,5,6]
#listeden 4 ve 5'i sil
del numbers[1:3]  #del liste[start:stop-1]
print(numbers)

[3, 6]


In [209]:
#sıralama:tersten
nums = [3,5,7,2,1,9]
nums.sort(reverse=True)  # sort aynı tip elemanlar üzerinde sırlama yapar
print(nums)

[9, 7, 5, 3, 2, 1]


In [210]:
nums = [3,5,7,2,1,9]
nums_copy = nums.sort()  #sort() inplace metot : yerinde değişiklik yapan bir metot
print(nums_copy)

None


In [212]:
nums = [3,5,7,2,1,9]
nums_copy = sorted(nums)  #sorted() ile doğrudan 
print(nums_copy)
print(nums)

[1, 2, 3, 5, 7, 9]
[3, 5, 7, 2, 1, 9]


In [213]:
# bir listeyi ters çevirme: reverse()
nums = [3,5,7,2,1,9]
tersi_nums = nums[::-1]
print(tersi_nums)

[9, 1, 2, 7, 5, 3]


In [216]:
# bir listeyi ters çevirme: reverse()
nums = [3,5,7,2,1,9]
tersi_nums = reversed(nums)
print(list(tersi_nums))

[9, 1, 2, 7, 5, 3]


In [214]:
# bir listeyi ters çevirme: reverse()
nums = [3,5,7,2,1,9]
nums.reverse()  #in-place metot, başka bir değişkene doğrudan aktarılmaz
print(nums)

[9, 1, 2, 7, 5, 3]


In [219]:
# Listeler ile kuyruk tasarımı/modellemesi
dosya = ["dosya1", "dosya2", "dosya3"]
# kuyruk sonuna eleman ekle
dosya.append("dosya4")
# FIFO: ilk giren ilk çıkar: kuyruktan ilk elemanı çıkarmak için
dosya.pop(0)  #ilk elemanı çıkarır
print(dosya)

['dosya2', 'dosya3', 'dosya4']


In [221]:
# Listeler ile kuyruk tasarımı/modellemesi-2
from collections import deque
dosya = ["dosya1", "dosya2", "dosya3"]
dosya = deque(dosya)
# kuyruk sonuna eleman ekle
dosya.append("dosya4")
# FIFO: ilk giren ilk çıkar: kuyruktan ilk elemanı çıkarmak için
dosya.popleft()  #ilk elemanı çıkarır
print(dosya)

deque(['dosya2', 'dosya3', 'dosya4'])


In [225]:
# 1-100 arası sayı üretip tek olanları alalım
nums = list(range(1,101))
nums_tek = nums[::2]
print(nums_tek)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [228]:
mix = [1, [1,"one",2,"two",3, "three"], 5, 6, 7, 73]
# mix içerisindeki stringleri nasıl alırız?
mix_str = mix[1][1::2]
mix_str

['one', 'two', 'three']

In [230]:
demet = 2,3,4
print(type(demet))

<class 'tuple'>


In [234]:
# tuple , listlerden daha az bellekte yer kaplar ve daha hızlı çalışır.
nums_list = list(range(1,101))
nums_demet = tuple(range(1,101))
import sys
print(sys.getsizeof(nums_list))  #byte cinsinden alanı belirtir
print(sys.getsizeof(nums_demet)) 

856
840


In [242]:
#hız testi: komut isteminden çalıştırın
!python3 -m timeit "tuple(range(1,101))"  #windows için python3 yerine py 

200000 loops, best of 5: 1.62 usec per loop


In [243]:
!python3 -m timeit "list(range(1,101))"

500000 loops, best of 5: 798 nsec per loop


In [237]:
e = "earth", "venus", "uranus"
print(e, type(e))

('earth', 'venus', 'uranus') <class 'tuple'>


In [235]:
e,v,u = "earth", "venus", "uranus"
print(e, type(e))

earth <class 'str'>


In [236]:
e,u = ("earth", "venus"), "uranus"
print(e, type(e))

('earth', 'venus') <class 'tuple'>


In [239]:
dir(tuple)[-2:]  # metot ve özellikleri listeler

['count', 'index']

In [241]:
dir(list)[-11:]  # metot ve özellikleri listeler

['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [244]:
#tuple immutable özelliği
e = "earth", "venus", "uranus"
e[1] = "mars"
print(e)

TypeError: ignored

In [245]:
mix = (1, [1,"one",2,"two",3, "three"], 5, 6, 7, 73, [2,"iki"])
#en son elemana nasıl erişirim
mix[-1]

[2, 'iki']

In [246]:
# unpacking(açma): tüm iterable nesnelere uygulanabilir
a,b,c = (1,2,3)
print(b)

2


In [247]:
a,b,c = "alim"
print(b)

ValueError: ignored

In [248]:
a,b,*c = "alim"
print(b)
print(c)

l
['i', 'm']


In [251]:
a,b = "alim"
print(b)

ValueError: ignored

In [252]:
a,*b = "alim"
print(b)

['l', 'i', 'm']


In [253]:
a,*b,c = (1,2,3,4,5,6,7,8,9)
print(a,"\n",b,"\n",c)

1 
 [2, 3, 4, 5, 6, 7, 8] 
 9


#Sözlük(dict)

In [254]:
musteri = {"meyve": "elma", "icki":"süt"}
musteri2 = dict(meyve="elma", icki="süt")   #burada değişken isimlendirme kurallarına uymalıyız
print(musteri)
print(musteri2)

{'meyve': 'elma', 'icki': 'süt'}
{'meyve': 'elma', 'icki': 'süt'}


In [255]:
musteri[0] #indis kullanılmaz

KeyError: ignored

In [256]:
musteri['meyve']  # key kullanılır 

'elma'

In [ ]:
help(zip)

In [260]:
list1= ['one', 'two', 'three']
list2 = [1, 2, 3]
birlesmis_liste = list(zip(list1,list2)) #demet halinde birleştirme yapar
print(birlesmis_liste)

[('one', 1), ('two', 2), ('three', 3)]


In [261]:
list1= ['one', 'two', 'three']
list2 = [1, 2, 3]
szlk = dict(zip(list1,list2)) #demet halinde birleştirme yapar
print(szlk)

{'one': 1, 'two': 2, 'three': 3}


In [257]:
# dict() unordered yapıdadır.
a = dict(one=1, two=2, three=3)
b = {'one': 1, 'two': 2, 'three': 3}
c = dict(zip(['one', 'two', 'three'], [1, 2, 3]))
d = dict([('two', 2), ('one', 1), ('three', 3)])
e = dict({'three': 3, 'one': 1, 'two': 2})
f = dict({'one': 1, 'three': 3}, two=2)
a == b == c == d == e == f

True

In [265]:
a = dict(one=1, two=2, three=3)
#reverse (ters çevirme)
print(a)
print(dict(reversed(a.items())))

{'one': 1, 'two': 2, 'three': 3}
{'three': 3, 'two': 2, 'one': 1}


In [267]:
# items() : key: value şeklinde tüm elemanları verir
# keys() : sadece key leri verir
# values() : sadece value ları verir
a = dict(one=1, two=2, three=3)
for i in a.items():
    print(i)

('one', 1)
('two', 2)
('three', 3)


In [268]:
a = dict(one=1, two=2, three=3)
for k,v in a.items():
    print(k, ":", v)

one : 1
two : 2
three : 3


In [270]:
#dict() metot listesi
dir(dict)[-11:]

['clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [274]:
tr_en = {"pazar":"sunday", "pazartesi":"monda", "salı":"tuesday", "çarşamba":"wednesday",
         "perşembe":"thursday", "cuma":"friday", "cumartesi":"saturday"}

ara = input("Türkçe gün adı.:")
en_ara = tr_en.get(ara, "aranan sözlükte yoktur")
print(en_ara)

Türkçe gün adı.:sedef
aranan sözlükte yoktur


In [277]:
# güncelleme için
tr_en.update(cumartesi="sat", hafta="weekday")
print(tr_en)

{'pazar': 'sunday', 'pazartesi': 'monda', 'salı': 'tuesday', 'çarşamba': 'wednesday', 'perşembe': 'thursday', 'cuma': 'friday', 'cumartesi': 'sat', 'hafta': 'weekday'}


In [280]:
#silmek için
sil = input("Silinecek Türkçe gün adı.:")
en_sil = tr_en.pop(sil, "Sözlükte yoktur")
print(en_sil)
print(tr_en)

Silinecek Türkçe gün adı.:dede
Sözlükte yoktur
{'pazar': 'sunday', 'pazartesi': 'monda', 'salı': 'tuesday', 'çarşamba': 'wednesday', 'perşembe': 'thursday', 'cuma': 'friday', 'cumartesi': 'sat'}
